server:
  port: 1998
spring:
  profiles:
    include:
      - mysql
      - security
      - redis
      - cloud
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis



